ALTER TABLE CP_SETCOLS ADD (
  PARAMS          VARCHAR2(2000 BYTE),
  VALIDATE_EVENT  VARCHAR2(4000 BYTE),
  MULTISELECT     VARCHAR2(5 BYTE)              DEFAULT 'N'                   NOT NULL,
  HIDE_COLS       VARCHAR2(2500 BYTE)
);

SET DEFINE OFF;
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'POS', 'NONE', 
    50, 'Pos', NULL, 5, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, '#AUTONUMBER_', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'ACCNO', 'NONE', 
    130, 'AC No', NULL, 30, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT ACCNO,NAME,PARENTACC FROM ACACCOUNT WHERE ACTYPE=0 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'NAME,ACCNO', NULL, 'ACCNO=ACCNO,ACNAME=NAME', 'parent=PARENTACC,code=ACCNO,title=NAME', 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from acaccount where accno='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);', 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'FCDEBIT', 'NONE', 
    150, 'DEBIT', NULL, 10, 'Y', 
    'ALIGN_RIGHT', 'MONEY_FORMAT', 'TEXTFIELD', NULL, 'color:green;text-align:end;', 
    NULL, '#NUMBER_0', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'FCCREDIT', 'NONE', 
    150, 'CREDIT', NULL, 20, 'Y', 
    'ALIGN_RIGHT', 'MONEY_FORMAT', 'TEXTFIELD', NULL, 'color:red;text-align:end;', 
    NULL, '#NUMBER_0', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.CURR', 'FORMAT_J2EE', 'NONE', 
    200, 'FORMAT', NULL, 30, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.CURR', 'CODE', 'NONE', 
    100, 'CODE', NULL, 10, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.CURR', 'RATE_DATE', 'NONE', 
    200, 'Rate Date', NULL, 20, 'Y', 
    'ALIGN_LEFT', 'SHORT_DATE_FORMAT', 'DATEFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'ACNAME', 'NONE', 
    300, 'NAME', NULL, 40, 'Y', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'DESCR', 'NONE', 
    350, 'DESCR', NULL, 50, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'INVKEYFLD', 'NONE', 
    100, 'Inv Keyfld', NULL, 75, 'N', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'INV_DESCR', 'NONE', 
    200, 'Inv Descr', NULL, 80, 'Y', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'COSTCENT', 'NONE', 
    100, 'COST CENT', NULL, 60, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,TITLE FROM ACCOSTCENT1 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'TITLE,CODE', NULL, 'COSTCENT=CODE,CSNAME=TITLE', NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'CSNAME', 'NONE', 
    150, 'TITLE', NULL, 70, 'Y', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'POS', 'NONE', 
    50, 'Pos', NULL, 5, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, '#AUTONUMBER_', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'FCDEBIT', 'NONE', 
    150, 'DEBIT', NULL, 10, 'Y', 
    'ALIGN_RIGHT', 'MONEY_FORMAT', 'TEXTFIELD', NULL, 'color:green;text-align:end;', 
    NULL, '#NUMBER_0', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'ACCNO', 'NONE', 
    130, 'AC No', NULL, 30, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT ACCNO,NAME,PARENTACC FROM ACACCOUNT WHERE ACTYPE=0 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'NAME,ACCNO', NULL, 'ACCNO=ACCNO,ACNAME=NAME', 'parent=PARENTACC,code=ACCNO,title=NAME', 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from acaccount where accno='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);', 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'ACNAME', 'NONE', 
    300, 'NAME', NULL, 40, 'Y', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'DESCR', 'NONE', 
    350, 'DESCR', NULL, 50, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'COSTCENT', 'NONE', 
    100, 'COST CENTER', NULL, 60, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,TITLE FROM ACCOSTCENT1 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'TITLE,CODE', NULL, 'COSTCENT=CODE,CSNAME=TITLE', NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'CSNAME', 'NONE', 
    150, 'TITLE', NULL, 70, 'N', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.PV1', 'CUST_CODE', 'NONE', 
    120, 'REFERENCE', NULL, 25, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,NAME,AC_NO FROM C_YCUST WHERE CHILDCOUNT=0 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'NAME,CODE', NULL, 'CUST_CODE=CODE,ACNAME=NAME,ACCNO=AC_NO', NULL, 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from C_YCUST where CODE='' + :newValue );
var ac_no = Util.getSQLValue(''select AC_NO from C_YCUST where CODE='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

var rn=table.indexOfRow(row);
table.getRows()[rn].getCells()[3].setEnabled(false); 

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACCNO'', ac_no);', 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'POS', 'NONE', 
    50, 'Pos', NULL, 5, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, '#AUTONUMBER_', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'FCCREDIT', 'NONE', 
    150, 'CREDIT', NULL, 10, 'Y', 
    'ALIGN_RIGHT', 'MONEY_FORMAT', 'TEXTFIELD', NULL, 'color:red;text-align:end;', 
    NULL, '#NUMBER_0', NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'ACCNO', 'NONE', 
    130, 'AC No', NULL, 30, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT ACCNO,NAME,PARENTACC FROM ACACCOUNT WHERE ACTYPE=0 ORDER BY PATH', NULL, 
    'NAME,ACCNO', NULL, 'ACCNO=ACCNO,ACNAME=NAME', 'parent=PARENTACC,code=ACCNO,title=NAME', 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from acaccount where accno='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);', 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'ACNAME', 'NONE', 
    300, 'NAME', NULL, 40, 'Y', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'DESCR', 'NONE', 
    350, 'DESCR', NULL, 50, 'Y', 
    'ALIGN_LEFT', 'NONE', 'TEXTFIELD', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'COSTCENT', 'NONE', 
    100, 'COST CENTER', NULL, 60, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,TITLE FROM ACCOSTCENT1 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'TITLE,CODE', NULL, 'COSTCENT=CODE,CSNAME=TITLE', NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'CSNAME', 'NONE', 
    150, 'TITLE', NULL, 70, 'N', 
    'ALIGN_LEFT', 'NONE', 'LABEL', NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.JV', 'CUST_CODE', 'NONE', 
    100, 'REFERENCE', NULL, 25, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,NAME,AC_NO FROM C_YCUST WHERE CHILDCOUNT=0 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'NAME,CODE', NULL, 'CUST_CODE=CODE,ACNAME=NAME,ACCNO=AC_NO', NULL, 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from C_YCUST where CODE='' + :newValue );
var ac_no = Util.getSQLValue(''select AC_NO from C_YCUST where CODE='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

var rn=table.indexOfRow(row);
table.getRows()[rn].getCells()[4].setEnabled(false); 

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACCNO'', ac_no);', 
    'N', NULL);
Insert into CP_SETCOLS
   (PROFILE, SETGRPCODE, ITEM_NAME, DISPLAY_TYPE, DISPLAY_WIDTH, DESCR, DESCRA, POSITION, GETFOCUS, ALIGN, USE_FORMAT, EDITOR_CLASS, LOV_SQL, OTHER_STYLES, LOOKUP_COLUMN, DEFAULT_VALUE, RETURN_VALUES, PARAMS, VALIDATE_EVENT, MULTISELECT, HIDE_COLS)
 Values
   (0, 'C7.RV1', 'CUST_CODE', 'NONE', 
    100, 'REFERENCE', NULL, 25, 'Y', 
    'ALIGN_LEFT', 'NONE', 'SEARCHFIELD', 'SELECT CODE,NAME,AC_NO FROM C_YCUST WHERE CHILDCOUNT=0 ORDER BY PATH', 'background-color:#fff0f5;text-align:end;', 
    'NAME,CODE', NULL, 'CUST_CODE=CODE,ACNAME=NAME,ACCNO=AC_NO', NULL, 'oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', "");
var sq = Util.getSQLValue(''select name from C_YCUST where CODE='' + :newValue );
var ac_no = Util.getSQLValue(''select AC_NO from C_YCUST where CODE='' + :newValue );
var child = Util.getSQLValue(''select childcount from acaccount where accno='' + :newValue );

var rn=table.indexOfRow(row);
table.getRows()[rn].getCells()[3].setEnabled(false); 

if (child>0) {
 sap.m.MessageToast.show(''Err ! , Cant select group a/c here..'');
}
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACNAME'', sq);
oModel.setProperty(currentRowoIndexContext.sPath + ''/ACCNO'', ac_no);', 
    'N', NULL);
COMMIT;
