
delete from sr7.c_contract;

delete from sr7.approval_all;

delete from sr7.fadep;

delete from sr7.faitems;

delete from sr7.facat;

delete from sr7.fatransaction;

delete from sr7.parameter;

delete from sr7.acaccount;

delete from sr7.accostcent1;

delete from sr7.acvoucher1;

delete from sr7.acvoucher2;

Delete from sr7.POSCUSTOMER;

Delete from sr7.POSPAYMENTS;

DELETE from sr7.POSPUR1;

DELETE from sr7.POSPUR2;

delete from sr7.invoice1;

delete from sr7.invoice2;

delete from sr7.order1;

delete from sr7.order2;


DELETE from sr7.INVUNPAID;

delete from sr7.userlog;

DELETE from sr7.PUR2;

delete from sr7.pur1;

delete from sr7.salesp;

delete from sr7.accostcent1;

delete from sr7.CBRANCH;

delete from sr7.C_CUSTITEMS;

DELETE from sr7.C_YCUST;

DELETE from sr7.CUSTITEMS;


delete from sr7.items;

delete from sr7.temporary;

delete from sr7.lcs_expenses;

delete from sr7.locations;

delete from sr7.invoicetype;

delete from sr7.store;

DELETE from sr7.ORDER1;

delete from sr7.c_order1;

delete from sr7.c_custitems;

delete from sr7.custitems;

delete from sr7.masterasm;


delete from sr7.stori;

insert into sr7.acaccount(ACCNO, GRPNO, NAME, NAMEA, ISCUST, LEVELNO, BEG_DRBAL, BEG_CRBAL, BEG_DRBALFC, BEG_CRBALFC, START_DATE, LASTUPDATE, LIMIT, COSTCENT, FLAG, TYPE, DEP_ACC, DEP_EXP, DEP_RATE, ISCHANGE, ISNEW, SUBGRP, KEYFLD, PATH, PARENTACC, TREELEVEL, CLOSEACC, ACTYPE, USECOUNT, CHILDCOUNT, ISSUPP, ISSALESP, ISBANKCASH, ISEMPLOYEE, FULL_ADDR, COUNTRY, AREA, CITY, TEL, FAX, REFERENCE_NAME, REFERENCE_TITLE, REFERENCE_TEL, EMAIL_ADDR, BANK_DETAILS, PAYMENT_TERMS, REMARKS, INVFLAG, CRD_LIMIT, DEFAULT_PRICE, ISFIXED, IS_ITEM_DISC_ALLOWED, IS_INV_DISC_ALLOWED, POSFLAG, BRANCHNO, CURRENCY_CODE, INV_DUE_DAYS, AC_NATURE, MOTHERCUST, USERNM, CREATDT)
select ACCNO, GRPNO, NAME, NAMEA, ISCUST, LEVELNO, BEG_DRBAL, BEG_CRBAL, BEG_DRBALFC, BEG_CRBALFC, START_DATE, LASTUPDATE, LIMIT, COSTCENT, FLAG, TYPE, DEP_ACC, DEP_EXP, DEP_RATE, ISCHANGE, ISNEW, SUBGRP, KEYFLD, PATH, PARENTACC, TREELEVEL, CLOSEACC, ACTYPE, USECOUNT, CHILDCOUNT, ISSUPP, ISSALESP, ISBANKCASH, ISEMPLOYEE, FULL_ADDR, COUNTRY, AREA, CITY, TEL, FAX, REFERENCE_NAME, REFERENCE_TITLE, REFERENCE_TEL, EMAIL_ADDR, BANK_DETAILS, PAYMENT_TERMS, REMARKS, INVFLAG, CRD_LIMIT, DEFAULT_PRICE, ISFIXED, IS_ITEM_DISC_ALLOWED, IS_INV_DISC_ALLOWED, POSFLAG, BRANCHNO, CURRENCY_CODE, 0 INV_DUE_DAYS, 1, MOTHERCUST, 'cr7', sysdate from sora.acaccount;

DELETE FROM SR7.ACACCOUNT WHERE PATH LIKE 'XXX\12000000000\1203\%' AND ACCNO!='1203';

UPDATE SR7.ACACCOUNT SET CHILDCOUNT=0 , USECOUNT=1 WHERE ACCNO='1203';

INSERT INTO SR7.ACVOUCHER1 (
   KEYFLD, PERIODCODE, NO, 
   VOU_CODE, TYPE, VOU_DATE, 
   CODE, CODEAMT, DESCR, 
   DEBAMT, CRDAMT, DUEDATE, 
   CREATDT, FLAG, USERNM, 
   YEAR, RCVFROM, SLSMN, 
   CODEACC, CHEQUENO, ISCHANGE, 
   ISNEW, BOOKSERIALNO, INVOICE_CODE, 
   INVOICE_TYPE, INVKEYFLD, REFERNO, 
   REFERCODE, REFERTYPE, PRINTCOUNT, 
   COSTCENT, REFERKEYFLD, FCCODE, 
   FCRATE, FCDEBAMT, FCCRDAMT, 
   FCCODEAMT, FC_MAIN_1, FC_MAIN_RATE_1, 
   APPROVED_BY, APPROVED_DATE, POSTED_BY, 
   POSTED_DATE) select    
   KEYFLD, PERIODCODE, NO, 
   VOU_CODE, TYPE, VOU_DATE, 
   CODE, CODEAMT, DESCR, 
   DEBAMT, CRDAMT, DUEDATE, 
   CREATDT, FLAG, USERNM, 
   YEAR, RCVFROM, SLSMN, 
   CODEACC, CHEQUENO, ISCHANGE, 
   ISNEW, BOOKSERIALNO, INVOICE_CODE, 
   INVOICE_TYPE, INVKEYFLD, REFERNO, 
   REFERCODE, REFERTYPE, PRINTCOUNT, 
   COSTCENT, REFERKEYFLD, FCCODE, 
   FCRATE, FCDEBAMT, FCCRDAMT, 
   FCCODEAMT, FC_MAIN_1, FC_MAIN_RATE_1, 
   'SR7' APPROVED_BY, SYSDATE APPROVED_DATE, 'SR7' POSTED_BY, 
   sysdate POSTED_DATE from sora.acvoucher1;
   
   
INSERT INTO SR7.ACVOUCHER2 (
   PERIODCODE, KEYFLD, NO, 
   VOU_CODE, VOU_DATE, POS, 
   ACCNO, DEBIT, CREDIT, 
   DESCR, DESCR2, FLAG, 
   USERNM, CREATDT, YEAR, 
   TYPE, ISCHANGE, ISNEW, 
   INVOICE_CODE, INVOICE_TYPE, INVKEYFLD, 
   GRPNO, REFERNO, REFERCODE, 
   REFERTYPE, COSTCENT, REFERKEYFLD, 
   FCCODE, FCRATE, FCDEBAMT, 
   FCCRDAMT, FCCODEAMT, UNIT_NUMBER, 
   PAIDYEAR, FCDEBIT, FCCREDIT, 
   FC_MAIN, FC_MAIN_RATE, CUST_CODE, 
   BRANCH_NO, CHEQUE_NO, DUE_DATE, 
   BKNO, FA_CODE) 
   SELECT    
   PERIODCODE, KEYFLD, NO, 
   VOU_CODE, VOU_DATE, POS, 
   ACCNO, DEBIT, CREDIT, 
   DESCR, DESCR2, FLAG, 
   USERNM, CREATDT, YEAR, 
   TYPE, ISCHANGE, ISNEW, 
   INVOICE_CODE, INVOICE_TYPE, INVKEYFLD, 
   GRPNO, REFERNO, REFERCODE, 
   REFERTYPE, COSTCENT, REFERKEYFLD, 
   FCCODE, FCRATE, FCDEBAMT, 
   FCCRDAMT, FCCODEAMT, UNIT_NUMBER, 
   PAIDYEAR, FCDEBIT, FCCREDIT, 
   FC_MAIN, FC_MAIN_RATE, CUST_CODE, 
   BRANCH_NO, CHEQUE_NO, DUE_DATE, 
   BKNO, '' FA_CODE FROM SORA.ACVOUCHER2;
   
   
   update acvoucher2
   set fcdebit=debit,fccredit=credit;

   INSERT INTO SR7.PUR1 (
   PERIODCODE, LOCATION_CODE, INVOICE_NO, 
   INVOICE_CODE, TYPE, INVOICE_DATE, 
   STARTDT, DUEDATE, STRA, 
   STRB, DEPTNO, SLSMN, 
   SECTION, CTG, MEMO, 
   INV_REF, INV_REFNM, INV_AMT, 
   DISC_AMT, INV_COST, FLAG, 
   YEAR, CREATDT, ISCLOSE, 
   ORDNO, LPNO, BKNO, 
   JVNO, KEYFLD, ADD_CHARGE, 
   POSTTYPE, ADD_CHARGEX, USERNAME, 
   PAIDAMT, ACNONSTK, PRINTCOUNT, 
   SUPINVNO, SHIPCO, INS_CO, 
   BANK, LCNO, INS_NO, 
   HANDLE_KD, FRGHT_KD, FRGHT_FC, 
   RATE, CURRENCY, WAGES, 
   CUSTOM_KD, INS_KD, BANK_CHG, 
   OTHER, KDCOST, CHG_NO, 
   CHG_KDAMT, CHG_CODE, CREDITACC, 
   CASHORBANKACC, FRIEGHTACC, ORD_NO, 
   ORDERNO, DELIVEREDG, DELIVERED, 
   PAIDTYPE2, PAIDAMT2, PAIDREF2, 
   PAIDAMT1, VEHICLE_NO, ADDR_AREA, 
   ADDR_BLOCK, ADDR_JEDDA, ADDR_STREET, 
   ADDR_BLDG, ADDR_TEL, REFERENCE_INFORMATION, 
   TOTQTY, C_CUS_NO, C_BRANCH_NO, 
   COSTCENT, ISSUED_DATE, RECIPT_DATE, 
   TOT_HAS_ISSUED, TOT_HAS_RECIEVED, NO_OF_ISSUES, 
   NO_OF_RECIEVED, TOT_DAMAGE_QTY) 
   SELECT 
   PERIODCODE, LOCATION_CODE, INVOICE_NO, 
   INVOICE_CODE, TYPE, INVOICE_DATE, 
   STARTDT, DUEDATE, STRA, 
   STRB, DEPTNO, SLSMN, 
   SECTION, CTG, MEMO, 
   INV_REF, INV_REFNM, INV_AMT, 
   DISC_AMT, INV_COST, FLAG, 
   YEAR, CREATDT, ISCLOSE, 
   ORDNO, LPNO, BKNO, 
   JVNO, KEYFLD, ADD_CHARGE, 
   POSTTYPE, ADD_CHARGEX, USERNAME, 
   PAIDAMT, ACNONSTK, PRINTCOUNT, 
   SUPINVNO, SHIPCO, INS_CO, 
   BANK, LCNO, INS_NO, 
   HANDLE_KD, FRGHT_KD, FRGHT_FC, 
   RATE, CURRENCY, WAGES, 
   CUSTOM_KD, INS_KD, BANK_CHG, 
   OTHER, KDCOST, CHG_NO, 
   CHG_KDAMT, CHG_CODE, CREDITACC, 
   CASHORBANKACC, FRIEGHTACC, ORD_NO, 
   ORDERNO, DELIVEREDG, DELIVERED, 
   PAIDTYPE2, PAIDAMT2, PAIDREF2, 
   PAIDAMT1, VEHICLE_NO, ADDR_AREA, 
   ADDR_BLOCK, ADDR_JEDDA, ADDR_STREET, 
   ADDR_BLDG, ADDR_TEL, REFERENCE_INFORMATION, 
   TOTQTY, C_CUS_NO, C_BRANCH_NO, 
   COSTCENT, NULL ISSUED_DATE, NULL RECIPT_DATE, 
    TOT_HAS_ISSUED,  TOT_HAS_RECIEVED,  NO_OF_ISSUES, 
    NO_OF_RECIEVED,  0 TOT_DAMAGE_QTY FROM SORA.PUR1;

INSERT INTO sr7.PUR2 (
   PERIODCODE, LOCATION_CODE, INVOICE_NO, 
   INVOICE_CODE, TYPE, ITEMPOS, 
   REFER, SYSDT, STRA, 
   STRB, PRICE, PKCOST, 
   DISC_AMT, PACK, PACKD, 
   UNITD, DAT, QTY, 
   PKQTY, FREEQTY, FREEPKQTY, 
   ALLQTY, PRD_DATE, EXP_DATE, 
   YEAR, ISCLOSE, FLAG, 
   ORDWAS, KEYFLD, PACKAGED, 
   ADDITIONAL_AMT, RATE, CURRENCY, 
   CREATDT, ORDERNO, DELIVEREDG, 
   DELIVERED, QTYIN, QTYOUT, 
   DISC_AMT_GROSS, STAND_NO, SIZE_OF, 
   SIZE_OF_DESCR, SLSMNXX, ADD_AMT_GROSS, 
   COSTCENT, ISSUED_DATE, RECIPT_DATE, 
   HAS_ISSUED, HAS_RECIEVED, ISSUED_KEYFLD, 
   RECIEVED_KEYFLD, FREE_ALLQTY, DAM_PKQTY, 
   DAM_QTY, DAM_ALLQTY, DAM_JV, 
   DESCR) SELECT
      PERIODCODE, LOCATION_CODE, INVOICE_NO, 
   INVOICE_CODE, TYPE, ITEMPOS, 
   REFER, SYSDT, STRA, 
   STRB, PRICE, PKCOST, 
   DISC_AMT, PACK, PACKD, 
   UNITD, DAT, QTY, 
   PKQTY, 0 FREEQTY, 0 FREEPKQTY, 
   ALLQTY, PRD_DATE, EXP_DATE, 
   YEAR, ISCLOSE, FLAG, 
   ORDWAS, KEYFLD, PACKAGED, 
   ADDITIONAL_AMT, RATE, CURRENCY, 
   CREATDT, ORDERNO, DELIVEREDG, 
   DELIVERED, QTYIN, QTYOUT, 
   DISC_AMT_GROSS, STAND_NO, SIZE_OF, 
   SIZE_OF_DESCR, SLSMNXX, ADD_AMT_GROSS, 
   COSTCENT, ISSUED_DATE, RECIPT_DATE, 
   HAS_ISSUED, HAS_RECIEVED, ISSUED_KEYFLD, 
   RECIEVED_KEYFLD, 0 FREE_ALLQTY, 0 DAM_PKQTY, 
   0 DAM_QTY, 0 DAM_ALLQTY, 0 DAM_JV, 
   NULL DESCR FROM SORA.PUR2;
   
Insert into SR7.C_YCUST
   (CODE, NAME, CRD_LIMIT, TYPE, PRICENO, AC_NO, FLAG, BCUST, ETYPE, PATH, LEVELNO, CHILDCOUNT, USECOUNT, BFBALANCE, ISCUST, ISSUPP, ISBANKCASH, ISFIXED, IS_ITEM_DISC_ALLOWED, IS_INV_DISC_ALLOWED, DEFAULT_PRICE, COMMISION_RATE)
 Values
   ('1', 'CUSTOMERS', 0, 'WHOLESALE', 1, '1203', 1, 'Marketting By SalesMan', 1, 'XXX\1\', 1, 0, 0, 0, 'Y', 'N', 'N', 'N', 'N', 'N', 0, 0);
COMMIT;

   
INSERT INTO SR7.C_YCUST (
   CODE, NAME, CRD_LIMIT, 
   NAMEA, SPONSOR, AREA, 
   TEL, ADDR, SALESP, 
   TYPE, PRICENO, LICENSE, 
   AC_NO, FLAG, EMAIL, 
   BDETAIL, BCUST, TERMOFPAY, 
   REMARK, REFERENCE, FAX, 
   PAGER, ETYPE, KEYFLD, 
   CURRENT_CONTRACT_ID, UPDATE_TIME, PARENTCUSTOMER, 
   PATH, LEVELNO, CHILDCOUNT, 
   USECOUNT, BFBALANCE, ISCUST, 
   ISSUPP, ISBANKCASH, ISFIXED, 
   IS_ITEM_DISC_ALLOWED, IS_INV_DISC_ALLOWED, DEFAULT_PRICE, 
   BF_JVKEYFLD, COMMISION_AC, REVENUE_AC, 
   COMMISION_RATE, CRE_LIMIT_TYPE, COLLECTORS, 
   MOV_TYPE) 
   SELECT   
   CODE, NAME, CRD_LIMIT, 
   NAMEA, SPONSOR, AREA, 
   TEL, ADDR, SALESP, 
   TYPE, PRICENO, LICENSE, 
   '1203' AC_NO, FLAG, EMAIL, 
   BDETAIL, BCUST, TERMOFPAY, 
   REMARK, REFERENCE, FAX, 
   PAGER, ETYPE, KEYFLD, 
   CURRENT_CONTRACT_ID, UPDATE_TIME,'1'  PARENTCUSTOMER, 
   'XXX\1\'||CODE PATH, 1 LEVELNO,0  CHILDCOUNT, 
   0 USECOUNT, 0 BFBALANCE, 'Y' ISCUST, 
   'N' ISSUPP, 'N' ISBANKCASH, 'N' ISFIXED, 
   'N' IS_ITEM_DISC_ALLOWED, 'N' IS_INV_DISC_ALLOWED, 0 DEFAULT_PRICE, 
   NULL BF_JVKEYFLD, NULL COMMISION_AC, NULL REVENUE_AC, 
   0 COMMISION_RATE, CRE_LIMIT_TYPE, COLLECTORS, 
   '' MOV_TYPE FROM SORA.C_YCUST;
INSERT INTO SR7.CBRANCH (
   BRNO, CODE, ACCNO, 
   B_NAME, B_NAMEA, SLSMN, 
   AREA, CITY, TEL, 
   FAX, KEYFLD, CONTRACT_KEYFLD, 
   UPDATE_TIME, DISCP) 
   SELECT
   BRNO, CODE, '1203' ACCNO, 
   B_NAME, B_NAMEA, SLSMN, 
   AREA, CITY, TEL, 
   FAX, KEYFLD, CONTRACT_KEYFLD, 
   UPDATE_TIME, DISCP
   FROM SORA.CBRANCH;

INSERT INTO SR7.C_CONTRACT (
   KEYFLD, NO, CONTRACT_TYPE, 
   CONTRACT_DATE, CUST_CODE, REF_TITLE, 
   REF_ADDRESS, REF_ID, TEL, 
   FAX, PROJECT_NAME, REMARKS, 
   END_PRICE_DATE, FLAG, PROJECT_ADDRESS, 
   REF_NAME, BRANCH_NO, PAYTERM, 
   PROJECT_NO, SALESP, DISCP, 
   COLLECTORS) 
SELECT KEYFLD, NO, CONTRACT_TYPE, 
   CONTRACT_DATE, CUST_CODE, REF_TITLE, 
   REF_ADDRESS, REF_ID, TEL, 
   FAX, PROJECT_NAME, REMARKS, 
   END_PRICE_DATE, FLAG, PROJECT_ADDRESS, 
   REF_NAME, BRANCH_NO, PAYTERM, 
   PROJECT_NO, SALESP, DISCP, 
   COLLECTORS FROM SORA.C_CONTRACT;
   
INSERT INTO SR7.C_CUSTITEMS (
   KEYFLD, STARTDATE, REFER, 
   PRICE, DESCR, PACKD, 
   UNITD, PACK, ENDDATE, 
   FLAG, UPDATE_TIME, DISC_AMT, 
   PRE_PRICE, PRE_DISC_AMT) 
   SELECT 
   KEYFLD, STARTDATE, REFER, 
   PRICE, DESCR, PACKD, 
   UNITD, PACK, ENDDATE, 
   FLAG, UPDATE_TIME, DISC_AMT, 
   PRE_PRICE, PRE_DISC_AMT
   FROM SORA.C_CUSTITEMS;

ALTER TABLE SR7.C_ORDER1
 DROP CONSTRAINT "ORDER1UniqueConstraint1";


ALTER TABLE SR7.C_ORDER1
 DROP CONSTRAINT PK_ORDER1;

ALTER TABLE SR7.C_ORDER1 ADD ORD_POS NUMBER DEFAULT 0 NOT NULL;

ALTER TABLE SR7.C_ORDER1 ADD (
  CONSTRAINT C_ORDER1_PKX
 PRIMARY KEY
 (LOCATION_CODE, PERIODCODE, ORD_NO, ORD_POS, ORD_CODE) DISABLE);


INSERT INTO C_ORDER1 (
   LOCATION_CODE, PERIODCODE, ORD_NO, 
   ORD_CODE, ORD_REF, ORD_REFNM, 
   ORD_DATE, ORD_SHIP, ORD_SHPDT, 
   ORD_AMT, ORD_DISCAMT, ORD_FLAG, 
   ORD_EMPNO, YEAR, REMARKS, 
   PAYTERM, VALIDATIY, ATTN, 
   KEYFLD, DELIVEREDQTY, ORDERDQTY, 
   SALEINV, ONAME, ROUNDS, 
   TMPLANTLEAVE, TMSITEARRIVAL, TMMIXINGSTART, 
   TMSITELEAVE, TMOFPLANARRIVAL, SANDQTY, 
   STONEQTY, CEMENTQTY, BLOCK, 
   STREET, JEDDA, AREA, 
   BLDG, TEL, OP_NO, 
   TYPOFCEM, TRUCKMIX, CHEMADD, 
   QTYWATER, TQTY, WGHT, 
   JOBNO, SALETYP, STRA, 
   ORDERED_KEY, USERNM, CREATDT, 
   SALESP, SALE_PRICE, SLNAME, 
   PLANT_NAME, PRODUCTION_TYPE, SAND_TYPE, 
   AGG_TYPE, CAST_TYPE, ISSUE_KEYFLD, 
   ISSUE_NO, ISSUE_PLANT_NO, CHEM_REFER) 
   SELECT 
    LOCATION_CODE, PERIODCODE, ORD_NO, 
   ORD_CODE, ORD_REF, ORD_REFNM, 
   ORD_DATE, ORD_SHIP, ORD_SHPDT, 
   ORD_AMT, ORD_DISCAMT, ORD_FLAG, 
   ORD_EMPNO, YEAR, REMARKS, 
   PAYTERM, VALIDATIY, ATTN, 
   KEYFLD, DELIVEREDQTY, ORDERDQTY, 
   SALEINV, ONAME, ROUNDS, 
   TMPLANTLEAVE, TMSITEARRIVAL, TMMIXINGSTART, 
   TMSITELEAVE, TMOFPLANARRIVAL, SANDQTY, 
   STONEQTY, CEMENTQTY, BLOCK, 
   STREET, JEDDA, AREA, 
   BLDG, TEL, OP_NO, 
   TYPOFCEM, TRUCKMIX, CHEMADD, 
   QTYWATER, TQTY, WGHT, 
   JOBNO, SALETYP, STRA, 
   ORDERED_KEY, USERNM, CREATDT, 
   SALESP, SALE_PRICE, SLNAME, 
   PLANT_NAME, PRODUCTION_TYPE, SAND_TYPE, 
   AGG_TYPE, CAST_TYPE, ISSUE_KEYFLD, 
   ISSUE_NO, ISSUE_PLANT_NO, '' CHEM_REFER
   FROM SORA.C_ORDER1;
   
   INSERT INTO SR7.ORDER1 (
   PERIODCODE, ORD_NO, ORD_CODE, 
   ORD_REF, ORD_REFNM, ORD_DATE, 
   ORD_SHIP, ORD_SHPDT, ORD_AMT, 
   ORD_DISCAMT, ORD_FLAG, ORD_EMPNO, 
   YEAR, REMARKS, PAYTERM, 
   VALIDATIY, ATTN, KEYFLD, 
   DELIVEREDQTY, ORDERDQTY, SALEINV, 
   ONAME, LOCATION_CODE, COSTCENT, 
   ORD_TYPE, RECIPT_KEYFLD, PUR_KEYFLD, 
   LCNO, ORDACC, APPROVED_BY, 
   APPROVED_TIME, LAST_MODIFIED_TIME, LAST_MODIFYED_BY, 
   DELIVERED_FREEQTY, PUR_ADJUST_KEYFLD, HAVE_ADJUSTMENT, 
   ADJUST_AMOUNT, ADJUST_CURRENCY, ADJUST_RATE, 
   ADJUST_DATE, ADJUST_DESCR, PUR_AND_SRV, 
   STRA, SAL_AND_ISS, ISSUE_KEYFLD, 
   ORD_REFERENCE, ORD_FC_RATE, ORD_FC_DESCR, 
   PAY_KEYFLD, SALERET_KEYFLD, SALERET, 
   ORD_TXT_WO, ORD_TXT_IID) 
   SELECT 
     PERIODCODE, ORD_NO, ORD_CODE, 
   ORD_REF, ORD_REFNM, ORD_DATE, 
   ORD_SHIP, ORD_SHPDT, ORD_AMT, 
   ORD_DISCAMT, ORD_FLAG, ORD_EMPNO, 
   YEAR, REMARKS, PAYTERM, 
   VALIDATIY, ATTN, KEYFLD, 
   DELIVEREDQTY, ORDERDQTY, SALEINV, 
   ONAME, LOCATION_CODE, COSTCENT, 
   ORD_TYPE, NULL RECIPT_KEYFLD, NULL PUR_KEYFLD, 
   NULL LCNO, '' ORDACC, 'CR7' APPROVED_BY, 
   SYSDATE APPROVED_TIME, NULL LAST_MODIFIED_TIME, 'SR7' LAST_MODIFYED_BY, 
   0 DELIVERED_FREEQTY, NULL PUR_ADJUST_KEYFLD, 'N' HAVE_ADJUSTMENT, 
   0 ADJUST_AMOUNT, 'KWD' ADJUST_CURRENCY, 1 ADJUST_RATE, 
   SYSDATE ADJUST_DATE, '' ADJUST_DESCR, 'N' PUR_AND_SRV, 
   1 STRA, 'N' SAL_AND_ISS, NULL ISSUE_KEYFLD, 
   NULL ORD_REFERENCE, 1 ORD_FC_RATE, 'KWD' ORD_FC_DESCR, 
   NULL PAY_KEYFLD, NULL SALERET_KEYFLD, 'N' SALERET, 
   '' ORD_TXT_WO, '' ORD_TXT_IID
   FROM SORA.ORDER1;  


INSERT INTO SR7.LOCATIONS (
   CODE, NAME, NAMEA, 
   FLAG, FROM_KEYFLD, TO_KEYFLD) 
    SELECT 
       CODE, NAME, NAMEA, 
   FLAG, FROM_KEYFLD, TO_KEYFLD
   FROM SORA.LOCATIONS;

INSERT INTO SR7.INVOICETYPE (
   NO, LOCATION_CODE, ACCNO, 
   DESCR, DESCRA, FLAG, 
   DEFAULT_SEQ) 
   SELECT
         NO, LOCATION_CODE, ACCNO, 
   DESCR, DESCRA, FLAG, 
   DEFAULT_SEQ FROM SORA.INVOICETYPE;

ALTER TABLE SR7.STORE
ADD SALADDACC VARCHAR2(500);

INSERT INTO SR7.STORE (
   NO, NAME, SPONSOR, 
   LICENSE, AREA, TEL, 
   SALESP, USERNAME, SALACC, 
   SALRACC, PURACC, PURRACC, 
   ADJPACC, ADJMACC, KEYFLD, 
   SALDISCACC, PURDISCACC, FLAG, 
   NAMEA, EXPACC, STOREACC, 
   SALADDACC) 
    SELECT
   NO, NAME, SPONSOR, 
   LICENSE, AREA, TEL, 
   SALESP, USERNAME, SALACC, 
   SALRACC, PURACC, PURRACC, 
   ADJPACC, ADJMACC, KEYFLD, 
   SALDISCACC, PURDISCACC, FLAG, 
   NAMEA, EXPACC, STOREACC, 
   SALADDACC FROM SORA.STORE;

INSERT INTO SR7.ITEMS (
   REFERENCE, BARCODE, DESCR, 
   DESCRA, LSPRICE, CTG, 
   PKAVER, LIFO, PRICE1, 
   PRICE2, PRICE3, PRICE4, 
   FIFO, PFSTORE, SAMPLE, 
   BALANCE, FREE, TESTER, 
   EXP_DT, TYPE, FLAG, 
   PUR_DATE, PACKD, UNITD, 
   PACK, ON_ORD, LPPRICE, 
   SUPP, STATUS, NXTSHIP, 
   FPCOST, LPCOST, ORDSUPP, 
   MFCODE, MDLCODE, PRD_DT, 
   SALORD, DAMAGE, SORD, 
   REMARK, TERMOFPAY, PARTNO, 
   ITPRICE1, ITPRICE2, ITPRICE3, 
   DESCR1, DESCR2, INDEG, 
   PHOTOFILE, ITPRICE4, KEYFLD, 
   PARENTITEM, LEVELNO, PATH, 
   HASLASTYEAR, USECOUNTS, CHILDCOUNTS, 
   SALACC, SALDISCACC, SALRACC, 
   PURACC, PURRACC, ADJPACC, 
   ADJMACC, QTYDENIED, HASEXPIRYDATE, 
   DEFAULT_PRICE, POSFLAG, PURDISCACC, 
   STAND_NO, POWER, EXPACC, 
   STOREACC, TOT_IN, TOT_OUT, 
   ORIG_ENG, ORIG_ARB) 
   SELECT
REFERENCE, BARCODE, DESCR, 
   DESCRA, LSPRICE, CTG, 
   PKAVER, LIFO, PRICE1, 
   PRICE2, PRICE3, PRICE4, 
   FIFO, PFSTORE, SAMPLE, 
   BALANCE, FREE, TESTER, 
   EXP_DT, TYPE, FLAG, 
   PUR_DATE, PACKD, UNITD, 
   PACK, ON_ORD, LPPRICE, 
   SUPP, STATUS, NXTSHIP, 
   FPCOST, LPCOST, ORDSUPP, 
   MFCODE, MDLCODE, PRD_DT, 
   SALORD, DAMAGE, SORD, 
   REMARK, TERMOFPAY, PARTNO, 
   ITPRICE1, ITPRICE2, ITPRICE3, 
   DESCR1, DESCR2, INDEG, 
   PHOTOFILE, ITPRICE4, KEYFLD, 
   PARENTITEM, LEVELNO, PATH, 
   HASLASTYEAR, USECOUNTS, CHILDCOUNTS, 
   SALACC, SALDISCACC, SALRACC, 
   PURACC, PURRACC, ADJPACC, 
   ADJMACC, QTYDENIED, HASEXPIRYDATE, 
   DEFAULT_PRICE, POSFLAG, PURDISCACC, 
   STAND_NO, POWER, EXPACC, 
   STOREACC, TOT_IN, TOT_OUT, 
   ORIG_ENG, ORIG_ARB
   FROM SORA.ITEMS;

    UPDATE SR7.SETUP
    SET VALUE='SR7' WHERE VARIABLE='MASTER_USER';
     
    UPDATE SR7.SETUP
    SET VALUE='SR7' WHERE VARIABLE='MASTER_OWNER';

    update c7_fiscals set master_owner='SR7';
                  

DECLARE
CURSOR ACS IS SELECT DISTINCT ACCNO,CODE,BRNO FROM SORA.CBRANCH;
BEGIN
FOR X IN ACS LOOP
UPDATE SR7.ACVOUCHER2
SET CUST_CODE=X.CODE ,BRANCH_NO=X.BRNO,ACCNO='1203' 
WHERE ACCNO=X.ACCNO;
END LOOP;
END;


update sr7.order1
set keyfld=ord_no

update sr7.c_order1
set keyfld=ord_no

insert into sr7.salesp
(NO, NAME, NAMEA, CIVILID, CRD_LIMIT, MOBILE, PAGER, 
SECTION, TYPE, FLAG, PASSNO, DLIC, RESID, HADDR, CADDR, 
PEXP, DEXP, RESDT, CEXP, JDATE, TDATE, KEYFLD, ACCOUNTNO, VEHICLENO, UPDATE_TIME)
select 
NO, NAME, NAMEA, CIVILID, CRD_LIMIT, MOBILE, PAGER, SECTION, 
TYPE, FLAG, PASSNO, DLIC, RESID, HADDR, CADDR, PEXP, DEXP, RESDT,
 CEXP, JDATE, TDATE, KEYFLD, ACCOUNTNO, VEHICLENO, UPDATE_TIME
 from sora.salesp;